version: "2.1"  # Compose file format v3 does not support health checks
services:
  web:
    build:
      dockerfile: dev.Dockerfile
    image: datalad-registry:dev
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment: &env
      FLASK_APP: "datalad_registry:create_app"

      DATALAD_REGISTRY_OPERATION_MODE: "${DATALAD_REGISTRY_OPERATION_MODE}"
      DATALAD_REGISTRY_INSTANCE_PATH: /app/instance
      DATALAD_REGISTRY_DATASET_CACHE: /data/cache

      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "redis://backend:6379"

      # db service access info
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
    command: [ "bash", "-c", "flask init-db && flask run --host=0.0.0.0" ]
    volumes:
      - ${WEB_PATH_AT_HOST}/instance:/app/instance

  worker:
    image: datalad-registry:dev
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    command: [
      "bash", "-c",
      "celery -A datalad_registry.make_celery:celery_app worker --loglevel DEBUG --pool prefork"
    ]
    volumes:
      - ${WORKER_PATH_AT_HOST}/data/cache:/data/cache
    environment:
      <<: *env
    healthcheck:
      test: [
        "CMD", "bash", "-c",
        "celery -A datalad_registry.make_celery:celery_app status --timeout 1 --json | grep -q pong"
      ]
      interval: 5s
      timeout: 3s
      retries: 10

  # Monitor for Celery service
  monitor:
    image: datalad-registry:dev
    depends_on:
      broker:
        condition: service_healthy
      worker:
        condition: service_healthy
    environment:
      <<: *env
      FLOWER_BROKER_API: "${FLOWER_BROKER_API}"
      FLOWER_PERSISTENT: "True"
      FLOWER_DB: "/data/flower"
      FLOWER_STATE_SAVE_INTERVAL: "1000"  # In milliseconds
      FLOWER_NATURAL_TIME: "True"
      FLOWER_BASIC_AUTH: "$FLOWER_BASIC_AUTH"
    ports:
      - "127.0.0.1:5555:5555"
    command: [ "bash", "-c", "celery -A datalad_registry.make_celery:celery_app flower" ]
    volumes:
      - ${MONITOR_PATH_AT_HOST}/data:/data
    healthcheck:
      test: [
        "CMD", "bash", "-c",
        "RESPONSE=$$(curl -s http://localhost:5555/healthcheck); if [ \"$$RESPONSE\" = \"OK\" ]; then exit 0; else exit 1; fi"
      ]
      interval: 30s
      timeout: 10s
      retries: 3

  # TODO: Currently, there is no job to be scheduled.
  #   Disable this to make debugging easier.
  #   Once there is a job to be scheduled, we can uncomment this to enable the scheduler
  #  scheduler:
  #    build: .
  #    depends_on:
  #      broker:
  #        condition: service_healthy
  #    command: [
  #      celery, -A, datalad_registry.runcelery.celery,
  #      beat,
  #      --loglevel, DEBUG,
  #      -s, /app/instance/celerybeat-schedule
  #    ]
  #    volumes:
  #      - ${DL_REGISTRY_INSTANCE_PATH}:/app/instance
  #    environment:
  #      <<: *env

  broker:
    image: docker.io/rabbitmq:3-management
    hostname: dlreg-broker
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - ${BROKER_PATH_AT_HOST}/home:/var/lib/rabbitmq
    healthcheck: # https://www.rabbitmq.com/monitoring.html#health-checks
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3

  # Result backend for Celery
  backend:
    image: docker.io/redis:7
    ports:
      - "127.0.0.1:6379:6379"

  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_INITDB_ARGS: --encoding utf8 --locale C
    ports:
      - "127.0.0.1:5432:5432"
    userns_mode: "keep-id"  # This has an effect only after podman-compose 1.0.3 possibly
      # See https://github.com/containers/podman-compose/issues/166
      # for details.
      # For podman-compose 1.0.3 or earlier, use
      # `PODMAN_USERNS=keep-id podman-compose up`

    volumes:
      - ${DB_PATH_AT_HOST}/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-q" ]
      interval: 30s
      timeout: 30s
      retries: 3
