version: "3"
services:
  broker:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    expose:
      - "5672"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dlreg
      POSTGRES_USER: dlreg
      POSTGRES_PASSWORD:
      POSTGRES_INITDB_ARGS: --encoding utf8 --locale C
    ports:
      - 5432:5432
    volumes:
      - ./instance/db:/var/lib/postgresql/data
