services:
  web:
    build:
      dockerfile: dev.Dockerfile
      ## Old docker-compose asked for context but this was still insufficient
      ## since it could then "link" the built image here to be used for the worker
      # context: .
    image: datalad-registry:dev
    ports:
      - "35000:5000"
    environment:
      FLASK_APP: "datalad_registry:create_app"

      DATALAD_REGISTRY_OPERATION_MODE: "${DATALAD_REGISTRY_OPERATION_MODE}"
      DATALAD_REGISTRY_INSTANCE_PATH: /app/instance
      DATALAD_REGISTRY_DATASET_CACHE: /data/cache

      # db service access info
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
    command: [ "bash", "-c", "flask init-db && flask run --host=0.0.0.0" ]
    volumes:
      - ${WEB_PATH_AT_HOST}/instance:/app/instance

    networks:
      - datalad-registry_default

networks:
  datalad-registry_default:
    external: true
