openapi: 3.0.0
info:
  title: DataLad Registry API
  version: 1.0.0
  description: |
    Registering new dataset URL
    ---------------------------

    Registering a new URL for a dataset consists of the following steps:
      * retrieving a challenge token
      * adding the challenge token to the specified git reference and
        making that change available via the URL
      * issuing a request to add the URL

servers:
  - url: /v1

components:
  schemas:
    ds_id:
      type: string
      format: uuid
      example: 6eeadb86-84be-11e6-b24c-002590f97d84
    url_encoded:
      type: string
      format: byte
      example: aHR0cHM6Ly9kYXRhc2V0cy5kYXRhbGFkLm9yZy9sYWJzL2hheGJ5L3JhaWRlcnMvLmdpdA==
  parameters:
    ds_id:
      name: ds_id
      required: true
      in: path
      description: dataset ID
      schema:
        $ref: "#/components/schemas/ds_id"
    url_encoded:
      name: url_encoded
      required: true
      in: path
      description: dataset URL (base64-encoded)
      schema:
        $ref: "#/components/schemas/url_encoded"
  responses:
    invalid-encoded-url:
      description: invalid encoded URL
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            {
              "message": "Invalid encoded URL"
            }

paths:
  /datasets/{ds_id}/urls/{url_encoded}/token:
    parameters:
      - $ref: "#/components/parameters/ds_id"
      - $ref: "#/components/parameters/url_encoded"
    get:
      summary: Return challenge token for registering a dataset URL
      description: |
        Get a challenge token for dataset and URL (base64-encoded
        using Python's URL-safe character set).
      operationId: dataset_urls.token.get
      responses:
        "200":
          description: challenge token
          headers:
            Cache-Control:
              description: Cache-Control header with max-age directive
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  ds_id:
                    $ref: "#/components/schemas/ds_id"
                  url:
                    type: string
                    description: dataset URL
                  ref:
                    type: string
                    description: challenge reference
                  token:
                    type: string
                    description: challenge token
              example:
                {
                  "ds_id": "6eeadb86-84be-11e6-b24c-002590f97d84",
                  "url": "https://datasets.datalad.org/labs/haxby/raiders/.git",
                  "ref": "refs/datalad-registry/0612a88655746eb05d73732e9cc5ea289253a53b",
                  "token": "0612a88655746eb05d73732e9cc5ea289253a53b"
                }
        "400":
          $ref: "#/components/responses/invalid-encoded-url"

  /datasets/{ds_id}/urls:
    parameters:
      - $ref: "#/components/parameters/ds_id"
    get:
      summary: Return list of registered URLs for a dataset
      operationId: dataset_urls.urls.get
      responses:
        "200":
          description: List of registered URLs
          content:
            application/json:
              schema:
                type: object
                properties:
                  ds_id:
                    $ref: "#/components/schemas/ds_id"
                  urls:
                    type: array
                    items:
                      type: string
              example:
                {
                  "ds_id": "6eeadb86-84be-11e6-b24c-002590f97d84",
                  "urls": ["https://datasets.datalad.org/labs/haxby/raiders/.git"]
                }
    post:
      summary: Add a new URL
      operationId: dataset_urls.urls.post
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                url:
                  type: string
                token:
                  type: string
                ref:
                  type: string
            example:
              {
                "url": "https://datasets.datalad.org/labs/haxby/raiders/.git",
                "token": "0612a88655746eb05d73732e9cc5ea289253a53b",
                "ref": "refs/datalad-registry/0612a88655746eb05d73732e9cc5ea289253a53b"
              }
      responses:
        "202":
          description: URL submitted
          headers:
            Location:
              description: URL to query for status information
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  ds_id:
                    $ref: "#/components/schemas/ds_id"
                  url_encoded:
                    $ref: "#/components/schemas/url_encoded"
              example:
                {
                  "ds_id": "6eeadb86-84be-11e6-b24c-002590f97d84",
                  "url_encoded": "aHR0cHM6Ly9kYXRhc2V0cy5kYXRhbGFkLm9yZy9sYWJzL2hheGJ5L3JhaWRlcnMvLmdpdA=="
                }
        "400":
          description: invalid data or unknown token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                {
                  "message": "Unknown token"
                }
        "410":
          description: expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                {
                  "message": "Expired token"
                }
  /datasets/{ds_id}/urls/{url_encoded}:
    parameters:
      - $ref: "#/components/parameters/ds_id"
      - $ref: "#/components/parameters/url_encoded"
    get:
      summary: Query status of added URL
      operationId: dataset_urls.url.get
      responses:
        "200":
          description: URL status
          content:
            application/json:
              schema:
                type: object
                properties:
                  ds_id:
                    $ref: "#/components/schemas/ds_id"
                  url:
                    type: string
                  status:
                    description: status of URL
                    type: string
                    enum:
                      - unknown
                      - known
                      - URL pending verification
                      - verification failed
                  info:
                    description: subset of collected information
                    type: object
              example:
                {
                  "ds_id": "6eeadb86-84be-11e6-b24c-002590f97d84",
                  "url": "https://datasets.datalad.org/labs/haxby/raiders/.git",
                  "status": "known",
                  "info": {
                    "annex_uuid": "524f92ba-0490-462a-9c7a-f8e4d928484a",
                    "head": "8dcb5e00a00e18e83056c5fe1978afe90d3e9f8f",
                    "head_describe": "v1"
                  },
                }
        "400":
          $ref: "#/components/responses/invalid-encoded-url"
    patch:
      summary: Announce that dataset at URL has been updated
      operationId: dataset_urls.url.patch
      responses:
        "202":
          description: Announcement received
        "400":
          $ref: "#/components/responses/invalid-encoded-url"
        "404":
          description: Unknown URL
  /datasets:
    get:
      summary: Return list of known dataset IDs
      operationId: datasets.datasets.get
      parameters:
        - in: query
          name: page
          schema:
            type: integer
      responses:
        "200":
          description: List of known dataset IDs
          content:
            application/json:
              schema:
                type: object
                properties:
                  prev:
                    type: string
                    nullable: true
                  next:
                    type: string
                    nullable: true
                  ds_ids:
                    type: array
                    items:
                      $ref: "#/components/schemas/ds_id"
              example:
                {
                  "prev": null,
                  "next": "/v1/datasets?page=2",
                  "ds_ids": ["6eeadb86-84be-11e6-b24c-002590f97d84"]
                }
