name: Shellcheck on scripts

on: [ push, pull_request ]

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
      - name: Set up system
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install shellcheck
      - uses: actions/checkout@v5
      - name: Run shellcheck
        run: |
          git grep -l -E '#!/bin/(bash|sh)' | xargs shellcheck
